=== herettix/root/projektOR/zad/OR Labos 6/PHP/gramatika.dtd
<!ELEMENT telefonski_imenik (osoba*)>

<!ELEMENT osoba (ime, prezime, telefon*, adresa?, mail_adresa*, zanimanje?, datum_rodjenja?)>
<!ATTLIST osoba oib CDATA #REQUIRED>
<!ATTLIST osoba kategorija (prijatelj | kolega | obitelj | bez_kategorije) #REQUIRED>

<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>

<!ELEMENT telefon (broj)>
<!ATTLIST telefon tip (mobilni | fiksni | telefaks) #REQUIRED>
<!ELEMENT broj (#PCDATA)>
<!ATTLIST broj pozivni_broj (099 | 098 | 097 | 095 | 092 | 091 | 043 | 035 | 020 | 052 | 047 | 048 | 049 | 053 | 040 | 031 | 034 | 051 | 044 | 021 | 022 | 042 | 033 | 032 | 023 | 01) #REQUIRED>

<!ELEMENT adresa (ulica, kucni_broj, mjesto, drzava)>
<!ELEMENT mjesto (#PCDATA)>
<!ATTLIST mjesto postanski_broj CDATA #REQUIRED>
<!ELEMENT ulica (#PCDATA)>
<!ELEMENT kucni_broj (#PCDATA)>
<!ELEMENT drzava (#PCDATA)>

<!ELEMENT mail_adresa (#PCDATA)>

<!ELEMENT zanimanje (kljucne_rijeci, naziv_tvrtke?)>
<!ATTLIST zanimanje vrsta_djelatnosti (sve_djelatnosti | transport | kultura | sport | trgovina | opce | financije | usluge | turizam | ostalo) #REQUIRED>
<!ELEMENT naziv_tvrtke (#PCDATA)>
<!ELEMENT kljucne_rijeci (#PCDATA)>

<!ELEMENT datum_rodjenja (#PCDATA)>

=== herettix/root/projektOR/zad/OR Labos 6/PHP/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE telefonski_imenik SYSTEM "gramatika.dtd">

<?xml-stylesheet type="text/xsl" href="pretvorba.xsl" ?>

<telefonski_imenik>
  <osoba oib="15242136442" kategorija="kolega">
    <ime>Cristiano</ime>
    <prezime>Ronaldo</prezime>
    <telefon tip="mobilni">
      <broj pozivni_broj="092">171-7328</broj>
    </telefon>
    <telefon tip="fiksni">
      <broj pozivni_broj="044">571-7177</broj>
    </telefon>
    <adresa>
      <ulica>Adamičeva</ulica>
      <kucni_broj>233</kucni_broj>
      <mjesto postanski_broj="21846">Đulovac</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>cristiano.ronaldo@gmail.com</mail_adresa>
    <datum_rodjenja>26.10.1999.</datum_rodjenja>
  </osoba>
  <osoba oib="15942389058" kategorija="prijatelj">
    <ime>Zlatan</ime>
    <prezime>Ibrahimovic</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="034">745-3654</broj>
    </telefon>
    <adresa>
      <ulica>Sudete Đure</ulica>
      <kucni_broj>217</kucni_broj>
      <mjesto postanski_broj="39880">Osijek</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>zlatan.ibrahimovic@gmail.com</mail_adresa>
    <zanimanje vrsta_djelatnosti="turizam">
      <kljucne_rijeci></kljucne_rijeci>
      <naziv_tvrtke></naziv_tvrtke>
    </zanimanje>
    <datum_rodjenja>22.7.1973.</datum_rodjenja>
  </osoba>
  <osoba oib="17005519807" kategorija="prijatelj">
    <ime>Lionel</ime>
    <prezime>Messi</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="044">164-1558</broj>
    </telefon>
    <telefon tip="telefaks">
      <broj pozivni_broj="032">247-3103</broj>
    </telefon>
    <adresa>
      <ulica>Sljemenska</ulica>
      <kucni_broj>571</kucni_broj>
      <mjesto postanski_broj="28562">Viljevo</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>lionel.messi@gmail.com</mail_adresa>
    <zanimanje vrsta_djelatnosti="opce">
      <kljucne_rijeci></kljucne_rijeci>
      <naziv_tvrtke></naziv_tvrtke>
    </zanimanje>
    <datum_rodjenja>1.7.1992.</datum_rodjenja>
  </osoba>
  <osoba oib="17792384233" kategorija="bez_kategorije">
    <ime>Samuel</ime>
    <prezime>Eto’o</prezime>
    <telefon tip="mobilni">
      <broj pozivni_broj="098">679-4367</broj>
    </telefon>
    <telefon tip="telefaks">
      <broj pozivni_broj="031">613-7094</broj>
    </telefon>
    <adresa>
      <ulica>Zoranićeve planine</ulica>
      <kucni_broj>548</kucni_broj>
      <mjesto postanski_broj="39379">Obrovac</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>samuel.etoo@gmail.com</mail_adresa>
    <zanimanje vrsta_djelatnosti="ostalo">
      <kljucne_rijeci></kljucne_rijeci>
      <naziv_tvrtke></naziv_tvrtke>
    </zanimanje>
    <datum_rodjenja>20.1.1997.</datum_rodjenja>
  </osoba>
  <osoba oib="19716496924" kategorija="prijatelj">
    <ime>Emmanuel</ime>
    <prezime>Adebayor</prezime>
    <telefon tip="mobilni">
      <broj pozivni_broj="092">492-6467</broj>
    </telefon>
    <telefon tip="fiksni">
      <broj pozivni_broj="048">653-5908</broj>
    </telefon>
    <adresa>
      <ulica>Knežija</ulica>
      <kucni_broj>57</kucni_broj>
      <mjesto postanski_broj="37817">Privlaka</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>emmanuel.adebayor@gmail.com</mail_adresa>
    <zanimanje vrsta_djelatnosti="ostalo">
      <kljucne_rijeci></kljucne_rijeci>
      <naziv_tvrtke></naziv_tvrtke>
    </zanimanje>
    <datum_rodjenja>12.11.1990.</datum_rodjenja>
  </osoba>
  <osoba oib="19755820671" kategorija="prijatelj">
    <ime>Karim</ime>
    <prezime>Benzema</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="033">140-4696</broj>
    </telefon>
    <telefon tip="fiksni">
      <broj pozivni_broj="048">243-2075</broj>
    </telefon>
    <adresa>
      <ulica>Sortina</ulica>
      <kucni_broj>618</kucni_broj>
      <mjesto postanski_broj="99894">Senj</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>karim.benzema@gmail.com</mail_adresa>
    <datum_rodjenja>1.2.1974.</datum_rodjenja>
  </osoba>
  <osoba oib="20095098472" kategorija="obitelj">
    <ime>Carlos</ime>
    <prezime>Tevez</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="020">314-4184</broj>
    </telefon>
    <adresa>
      <ulica>Kozari put</ulica>
      <kucni_broj>143</kucni_broj>
      <mjesto postanski_broj="34046">Mljet</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>carlos.tevez@gmail.com</mail_adresa>
    <datum_rodjenja>25.9.1984.</datum_rodjenja>
  </osoba>
  <osoba oib="20737229934" kategorija="obitelj">
    <ime>John</ime>
    <prezime>Terry</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="033">519-7443</broj>
    </telefon>
    <telefon tip="mobilni">
      <broj pozivni_broj="099">129-1787</broj>
    </telefon>
    <adresa>
      <ulica>Remetinec</ulica>
      <kucni_broj>456</kucni_broj>
      <mjesto postanski_broj="92702">Klana</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>john.terry@gmail.com</mail_adresa>
    <datum_rodjenja>24.8.1991.</datum_rodjenja>
  </osoba>
  <osoba oib="21267596797" kategorija="obitelj">
    <ime>Frank</ime>
    <prezime>Lampard</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="023">720-6383</broj>
    </telefon>
    <adresa>
      <ulica>Orešići</ulica>
      <kucni_broj>162</kucni_broj>
      <mjesto postanski_broj="50871">Trpanj</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>frank.lampard@gmail.com</mail_adresa>
    <datum_rodjenja>18.11.1978.</datum_rodjenja>
  </osoba>
  <osoba oib="21832883348" kategorija="prijatelj">
    <ime>Thierry</ime>
    <prezime>Henry</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="022">276-5519</broj>
    </telefon>
    <adresa>
      <ulica>Janečeka, gustava</ulica>
      <kucni_broj>433</kucni_broj>
      <mjesto postanski_broj="90038">Mihovljan</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>thierry.henry@gmail.com</mail_adresa>
    <datum_rodjenja>14.11.1984.</datum_rodjenja>
  </osoba>
  <osoba oib="23987531493" kategorija="obitelj">
    <ime>Steven</ime>
    <prezime>Gerrard</prezime>
    <telefon tip="mobilni">
      <broj pozivni_broj="098">976-2499</broj>
    </telefon>
    <telefon tip="fiksni">
      <broj pozivni_broj="043">661-7986</broj>
    </telefon>
    <adresa>
      <ulica>Vrbovska</ulica>
      <kucni_broj>247</kucni_broj>
      <mjesto postanski_broj="95774">Buje</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>steven.gerrard@gmail.com</mail_adresa>
    <datum_rodjenja>19.9.1986.</datum_rodjenja>
  </osoba>
  <osoba oib="24456652397" kategorija="obitelj">
    <ime>Daniel</ime>
    <prezime>Alves</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="031">719-4728</broj>
    </telefon>
    <telefon tip="mobilni">
      <broj pozivni_broj="095">349-3266</broj>
    </telefon>
    <adresa>
      <ulica>Čigiri</ulica>
      <kucni_broj>669</kucni_broj>
      <mjesto postanski_broj="39569">Zagvozd</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>daniel.alves@gmail.com</mail_adresa>
    <zanimanje vrsta_djelatnosti="ostalo">
      <kljucne_rijeci></kljucne_rijeci>
      <naziv_tvrtke></naziv_tvrtke>
    </zanimanje>
    <datum_rodjenja>2.3.1982.</datum_rodjenja>
  </osoba>
  <osoba oib="24835534574" kategorija="kolega">
    <ime>Michael</ime>
    <prezime>Ballack</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="040">246-2554</broj>
    </telefon>
    <adresa>
      <ulica>Pirinova ulica</ulica>
      <kucni_broj>536</kucni_broj>
      <mjesto postanski_broj="33387">Vratišinec</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>michael.ballack@gmail.com</mail_adresa>
    <datum_rodjenja>5.1.1987.</datum_rodjenja>
  </osoba>
  <osoba oib="25815692130" kategorija="prijatelj">
    <ime>Rio</ime>
    <prezime>Ferdinand</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="031">548-5855</broj>
    </telefon>
    <telefon tip="mobilni">
      <broj pozivni_broj="099">555-7345</broj>
    </telefon>
    <adresa>
      <ulica>Nodilova</ulica>
      <kucni_broj>236</kucni_broj>
      <mjesto postanski_broj="52771">Gradište</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>rio.ferdinand@gmail.com</mail_adresa>
    <datum_rodjenja>7.5.1976.</datum_rodjenja>
  </osoba>
  <osoba oib="26260939272" kategorija="kolega">
    <ime>Kolo</ime>
    <prezime>Toure</prezime>
    <telefon tip="mobilni">
      <broj pozivni_broj="091">981-1986</broj>
    </telefon>
    <adresa>
      <ulica>Šipkovica</ulica>
      <kucni_broj>126</kucni_broj>
      <mjesto postanski_broj="86279">Rovinj</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>kolo.toure@gmail.com</mail_adresa>
    <datum_rodjenja>12.6.1995.</datum_rodjenja>
  </osoba>
  <osoba oib="26287049073" kategorija="prijatelj">
    <ime>Wayne</ime>
    <prezime>Rooney</prezime>
    <telefon tip="telefaks">
      <broj pozivni_broj="021">600-7165</broj>
    </telefon>
    <adresa>
      <ulica>Požarinje 7</ulica>
      <kucni_broj>778</kucni_broj>
      <mjesto postanski_broj="16865">Rešetari</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>wayne.rooney@gmail.com</mail_adresa>
    <datum_rodjenja>12.11.1982.</datum_rodjenja>
  </osoba>
  <osoba oib="27748380487" kategorija="obitelj">
    <ime>Iker</ime>
    <prezime>Casillas</prezime>
    <telefon tip="fiksni">
      <broj pozivni_broj="020">587-4976</broj>
    </telefon>
    <adresa>
      <ulica>Žuti jarak</ulica>
      <kucni_broj>24</kucni_broj>
      <mjesto postanski_broj="47307">Višnjan</mjesto>
      <drzava>Hrvatska</drzava>
    </adresa>
    <mail_adresa>iker.casillas@gmail.com</mail_adresa>
    <datum_rodjenja>26.9.1997.</datum_rodjenja>
  </osoba>
  <osoba oib="28758944502" kategorija="obitelj">
